# Intro to Bayesian Statistics Lab

Complete the following set of exercises to solidify your knowledge of Bayesian statistics and Bayesian data analysis.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1. Cookie Problem

Suppose we have two bowls of cookies. Bowl 1 contains 30 vanilla cookies and 10 chocolate cookies. Bowl 2 contains 20 of each. You randomly pick one cookie out of one of the bowls, and it is vanilla. Use Bayes Theorem to calculate the probability that the vanilla cookie you picked came from Bowl 1?

In [3]:
def bayes_rule(priors, likelihoods):
    marg = sum(np.multiply(priors, likelihoods))
    post = np.divide(np.multiply(priors, likelihoods), marg)
    return post

priors = [1/2, 1/2]
likelihoods = [(30/40), (0.5)]

bayes_rule(priors, likelihoods)

array([0.6, 0.4])

What is the probability that it came from Bowl 2?

In [ ]:
#la probabilidad de que la galleta de vainilla venga del Bowl 1 es del 60%

What if the cookie you had picked was chocolate? What are the probabilities that the chocolate cookie came from Bowl 1 and Bowl 2 respectively?

In [4]:
priors = [1/2, 1/2]
likelihoods_choc = [(0.25), (0.5)]
bayes_rule(priors, likelihoods_choc)

array([0.33333333, 0.66666667])

In [ ]:
#hay un 33.33% de probabilidades de que la galleta de chocolate saliera del Bowl1, y un 66.67% de que sea del Bowl2

## 2. Candy Problem

Suppose you have two bags of candies:

- In Bag 1, the mix of colors is:
    - Brown - 30%
    - Yellow - 20%
    - Red - 20%
    - Green - 10%
    - Orange - 10%
    - Tan - 10%
    
- In Bag 2, the mix of colors is:
    - Blue - 24%
    - Green - 20%
    - Orange - 16%
    - Yellow - 14%
    - Red - 13%
    - Brown - 13%
    
Not knowing which bag is which, you randomly draw one candy from each bag. One is yellow and one is green. What is the probability that the yellow one came from the Bag 1?

*Hint: For the likelihoods, you will need to multiply the probabilities of drawing yellow from one bag and green from the other bag and vice versa.*

In [6]:
priors = [1/2, 1/2]
likelihoods_bags = [(0.2)*(0.2),(0.10*0.14)]

bayes_rule(priors, likelihoods_bags)

array([0.74074074, 0.25925926])

In [ ]:
#la probabilidad de que la amarilla venga de la Bolsa1 es 74.07%

What is the probability that the yellow candy came from Bag 2?

In [ ]:
#25.92%

What are the probabilities that the green one came from Bag 1 and Bag 2 respectively?

In [ ]:
#la probabilidad de que la verde venga de la bolsa 1 es 25.92%, y de la Bolsa2 es 74.07%

## 3. Monty Hall Problem

Suppose you are a contestant on the popular game show *Let's Make a Deal*. The host of the show (Monty Hall) presents you with three doors - Door A, Door B, and Door C. He tells you that there is a sports car behind one of them and if you choose the correct one, you win the car!

You select Door A, but then Monty makes things a little more interesting. He opens Door B to reveal that there is no sports car behind it and asks you if you would like to stick with your choice of Door A or switch your choice to Door C. Given this new information, what are the probabilities of you winning the car if you stick with Door A versus if you switch to Door C?

In [10]:
priors = [1/2, 1/2]
likelihoods_doors = [0.5,0.5]
bayes_rule(priors, likelihoods_doors)

array([0.5, 0.5])

## 4. Bayesian Analysis 

Suppose you work for a landscaping company, and they want to advertise their service online. They create an ad and sit back waiting for the money to roll in. On the first day, the ad sends 100 visitors to the site and 14 of them sign up for landscaping services. Create a generative model to come up with the posterior distribution and produce a visualization of what the posterior distribution would look like given the observed data.

In [13]:
import pandas as pd

n_draws = 100000
prior = pd.Series(np.random.uniform(0, 1, size=n_draws))

def generative_model(param):
    result = np.random.binomial(100, param)
    return result

observed = 14

sim_data = list()

for p in prior:
    sim_data.append(generative_model(p))
    
posterior = prior[list(map(lambda x: x == observed, sim_data))]

posterior.hist()

Produce a set of descriptive statistics for the posterior distribution.

In [14]:
posterior.describe()

count    978.000000
mean       0.146541
std        0.035117
min        0.060698
25%        0.120779
50%        0.146133
75%        0.170698
max        0.257371
dtype: float64

What is the 90% credible interval range?

In [15]:
print(posterior.quantile(.025), '|', posterior.quantile(.975))

0.08470502365139752 | 0.22010395682865497


What is the Maximum Likelihood Estimate?

In [16]:
rounded = posterior.round(2)
mode = rounded.mode()[0]
probability = list(rounded).count(mode)/len(rounded)
print('Maximum Likelihood Estimate: ', mode, '|',probability)


Maximum Likelihood Estimate:  0.15 | 0.10633946830265849
