In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.
print(np.version.version)

1.16.0


In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
import random
a = np.random.random((2,3,5))
#4. Print a.
print (a)

[[[0.90797584 0.17809686 0.36438064 0.76128982 0.20084273]
  [0.42998047 0.7757803  0.33687512 0.49082041 0.22023132]
  [0.5788054  0.63316548 0.91361575 0.12510869 0.94239104]]

 [[0.87123983 0.61393518 0.62367533 0.35623757 0.92371019]
  [0.4330459  0.19627841 0.12238906 0.88338079 0.43697679]
  [0.5366209  0.20916148 0.36837676 0.70917406 0.6143598 ]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5, 2, 3))
#6. Print b.
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
#7. Do a and b have the same size? How do you prove that in Python code?
print (a.size)
print (b.size)

30
30


In [7]:
(a.size) == (b.size)

True

In [21]:
#8. Are you able to add a and b? Why or why not?
np.add(a,b) #No se puede hacer, no tienen la misma dimension.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [11]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b)
print (c)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [12]:
c = c.reshape(2, 3, 5)
print (c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [27]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = np.add(a,c)

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print (d)
print (a)

#los elementos de a son todos -1 con respecto a los elementos de d

[[[1.90797584 1.17809686 1.36438064 1.76128982 1.20084273]
  [1.42998047 1.7757803  1.33687512 1.49082041 1.22023132]
  [1.5788054  1.63316548 1.91361575 1.12510869 1.94239104]]

 [[1.87123983 1.61393518 1.62367533 1.35623757 1.92371019]
  [1.4330459  1.19627841 1.12238906 1.88338079 1.43697679]
  [1.5366209  1.20916148 1.36837676 1.70917406 1.6143598 ]]]
[[[0.90797584 0.17809686 0.36438064 0.76128982 0.20084273]
  [0.42998047 0.7757803  0.33687512 0.49082041 0.22023132]
  [0.5788054  0.63316548 0.91361575 0.12510869 0.94239104]]

 [[0.87123983 0.61393518 0.62367533 0.35623757 0.92371019]
  [0.4330459  0.19627841 0.12238906 0.88338079 0.43697679]
  [0.5366209  0.20916148 0.36837676 0.70917406 0.6143598 ]]]


In [53]:
#12. Multiply a and c. Assign the result to e.
c = c.reshape(2, 3, 5)
print (c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [15]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a,c)
print(e)

[[[0.90797584 0.17809686 0.36438064 0.76128982 0.20084273]
  [0.42998047 0.7757803  0.33687512 0.49082041 0.22023132]
  [0.5788054  0.63316548 0.91361575 0.12510869 0.94239104]]

 [[0.87123983 0.61393518 0.62367533 0.35623757 0.92371019]
  [0.4330459  0.19627841 0.12238906 0.88338079 0.43697679]
  [0.5366209  0.20916148 0.36837676 0.70917406 0.6143598 ]]]


In [57]:
#13. Does e equal to a? Why or why not?
a == e #Si, se estaba multiplicando el valor de a por puros 1s, por lo que se mantendra el valor de a en e y serán iguales.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [28]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.mean(d)
d_min = np.min(d)
d_mean = np.max(d)

print (d_max)
print (d_min)
print (d_mean)

1.525264064461113
1.1223890609396792
1.9423910403050564


In [19]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))

[[[0.90797584 0.17809686 0.36438064 0.76128982 0.20084273]
  [0.42998047 0.7757803  0.33687512 0.49082041 0.22023132]
  [0.5788054  0.63316548 0.91361575 0.12510869 0.94239104]]

 [[0.87123983 0.61393518 0.62367533 0.35623757 0.92371019]
  [0.4330459  0.19627841 0.12238906 0.88338079 0.43697679]
  [0.5366209  0.20916148 0.36837676 0.70917406 0.6143598 ]]]


In [26]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.
    
    
f[(d>d_min)&(d<d_mean)]=25
f[(d>d_mean)&(d<d_max)]=75
f[d==d_mean]=50
f[d==d_min]=0
f[d==d_max]=100
    
print(f)

[[[25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 50.]]

 [[25. 25. 25. 25. 25.]
  [25. 25.  0. 25. 25.]
  [25. 25. 25. 25. 25.]]]


In [31]:
#17. Print d and f. Do you have your expected f?
print(d)
print(f)
#yes!
#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        #[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        #[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       #[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        #[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        #[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
        #[ 75.,  75.,  25.,  25.,  25.],
        #[ 75.,  25.,  75.,  75.,  75.]],

       #[[ 25.,  25.,  25.,  25., 100.],
        #[ 75.,  75.,  75.,  75.,  75.],
        #[ 25.,  75.,   0.,  75.,  75.]]])

[[[1.90797584 1.17809686 1.36438064 1.76128982 1.20084273]
  [1.42998047 1.7757803  1.33687512 1.49082041 1.22023132]
  [1.5788054  1.63316548 1.91361575 1.12510869 1.94239104]]

 [[1.87123983 1.61393518 1.62367533 1.35623757 1.92371019]
  [1.4330459  1.19627841 1.12238906 1.88338079 1.43697679]
  [1.5366209  1.20916148 1.36837676 1.70917406 1.6143598 ]]]
[[[25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 50.]]

 [[25. 25. 25. 25. 25.]
  [25. 25.  0. 25. 25.]
  [25. 25. 25. 25. 25.]]]


In [37]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values ("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
#Again, you don't need Numpy in this question.

array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])

array.shape

TypeError: 'list' object is not callable